auxiliary_data_dir: /g/data/xp65/public/apps/cartopy-data
input_files:
- /scratch/w40/cb4968/esmvaltool_output/recipe_20240313_225743/preproc/timeseries/tas_amsterdam/metadata.yml
- /scratch/w40/cb4968/esmvaltool_output/recipe_20240313_225743/preproc/timeseries/tas_global/metadata.yml
log_level: info
output_file_type: png
plot_dir: /scratch/w40/cb4968/esmvaltool_output/recipe_20240313_225743/plots/timeseries/script1
quickplot:
  plot_type: plot
realms:
- atmos
recipe: recipe.yml
run_dir: /scratch/w40/cb4968/esmvaltool_output/recipe_20240313_225743/run/timeseries/script1
script: script1
themes:
- phys
version: 2.10.0
work_dir: /scratch/w40/cb4968/esmvaltool_output/recipe_20240313_225743/work/timeseries/script1
