auxiliary_data_dir: /g/data/xp65/public/apps/cartopy-data
input_files:
- /scratch/w40/cb4968/esmvaltool_output/recipe_20240313_225743/preproc/map/tas/metadata.yml
log_level: info
output_file_type: png
plot_dir: /scratch/w40/cb4968/esmvaltool_output/recipe_20240313_225743/plots/map/script1
quickplot:
  cmap: Reds
  plot_type: pcolormesh
realms:
- atmos
recipe: recipe.yml
run_dir: /scratch/w40/cb4968/esmvaltool_output/recipe_20240313_225743/run/map/script1
script: script1
themes:
- phys
version: 2.10.0
work_dir: /scratch/w40/cb4968/esmvaltool_output/recipe_20240313_225743/work/map/script1
